# =============================================================================
# Auto-labeling Configuration for Connect-Star Monorepo
# =============================================================================
# This file defines rules for automatically labeling PRs based on file changes
# =============================================================================

# -----------------------------------------------------------------------------
# Applications
# -----------------------------------------------------------------------------
'app:web':
  - changed-files:
    - any-glob-to-any-file: 'apps/web/**'

'app:mobile':
  - changed-files:
    - any-glob-to-any-file: 'apps/mobile/**'

# -----------------------------------------------------------------------------
# Packages
# -----------------------------------------------------------------------------
'pkg:ui':
  - changed-files:
    - any-glob-to-any-file: 'packages/ui/**'

'pkg:game-logic':
  - changed-files:
    - any-glob-to-any-file: 'packages/game-logic/**'

'pkg:api-client':
  - changed-files:
    - any-glob-to-any-file: 'packages/api-client/**'

'pkg:types':
  - changed-files:
    - any-glob-to-any-file: 'packages/types/**'

# -----------------------------------------------------------------------------
# Infrastructure & Tooling
# -----------------------------------------------------------------------------
'ci/cd':
  - changed-files:
    - any-glob-to-any-file: 
      - '.github/**'
      - '.husky/**'
      - 'scripts/**'
      - 'turbo.json'

'docker':
  - changed-files:
    - any-glob-to-any-file:
      - '**/Dockerfile'
      - '**/docker-compose*.yml'
      - '.dockerignore'
      - 'Makefile'

'config':
  - changed-files:
    - any-glob-to-any-file:
      - '*.json'
      - '*.js'
      - '*.ts'
      - '.env*'
      - '.*rc*'
      - '*.config.*'

'dependencies':
  - changed-files:
    - any-glob-to-any-file:
      - 'package.json'
      - 'pnpm-lock.yaml'
      - '**/package.json'

'docs':
  - changed-files:
    - any-glob-to-any-file:
      - '**/*.md'
      - 'docs/**'

'tests':
  - changed-files:
    - any-glob-to-any-file:
      - '**/*.test.*'
      - '**/*.spec.*'
      - '**/jest.config.*'
      - '**/__tests__/**'

# -----------------------------------------------------------------------------
# Code Categories
# -----------------------------------------------------------------------------
'frontend':
  - changed-files:
    - any-glob-to-any-file:
      - 'apps/web/**'
      - 'apps/mobile/**'
      - 'packages/ui/**'

'backend':
  - changed-files:
    - any-glob-to-any-file:
      - 'packages/api-client/**'

'shared':
  - changed-files:
    - any-glob-to-any-file:
      - 'packages/game-logic/**'
      - 'packages/types/**'

# -----------------------------------------------------------------------------
# Change Size (approximate)
# -----------------------------------------------------------------------------
'size:small':
  - changed-files:
    - any-glob-to-any-file: '*'
    - count: '1-10'

'size:medium':
  - changed-files:
    - any-glob-to-any-file: '*'
    - count: '11-30'

'size:large':
  - changed-files:
    - any-glob-to-any-file: '*'
    - count: '31+'